version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command:
      - "--max_allowed_packet=512000000"
      - "--innodb_log_file_size=2048000000"
      - "--innodb_log_files_in_group=4"
    volumes:
      - ~/Docker/mysql:/var/lib/mysql

volumes:
  mysql:
