version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ~/Docker/postgresql:/var/lib/postgresql/data

volumes:
  postgres:
